name: daily_routine_tracker
description: DRT to help monitor health progress
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.18.0
  const_to_enum_annotations:
    git:
      url: https://github.com/Vedsaga/const_to_enum_annotations.git
      ref: main
  dartz: ^0.10.1
  dio: ^5.4.0
  drift: ^2.14.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlcipher_flutter_libs: ^0.6.0
  sqlite3: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  const_to_enum_generator:
    git:
      url: https://github.com/Vedsaga/const_to_enum_generator.git
      ref: main
  drift_dev: ^2.14.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.0
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
